//===----------------------------------------------------------------------===//
// Catch2 tests for the WS-C modules: ORT engine (tabfm_ort_engine), device/EP
// layer (tabfm_devices) and DB-instance state (tabfm_state).
//
// Fixtures: test/fixtures/ort_engine/* are generated by gen_mlp_fixture.py
// (committed, deterministic — see that script). The WS-A fixture-model parity
// test additionally uses test/fixtures/{graph_fixture.onnx, model.safetensors,
// golden.json}; those are produced concurrently by workstream WS-A, so that
// test WARNs and skips when they are absent.
//===----------------------------------------------------------------------===//

#include "catch.hpp"

#include "duckdb.hpp"
#include "tabfm_ort_engine.hpp"
#include "tabfm_state.hpp"

// DuckDB's vendored yyjson (linked inside duckdb_static); the test object
// library only carries src/include + catch on its include path, so reach the
// header relative to this file.
#include "../../duckdb/third_party/yyjson/include/yyjson.hpp"

#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <unordered_map>

using namespace duckdb;
using namespace duckdb::anofox;
using namespace duckdb_yyjson;

namespace {

//===----------------------------------------------------------------------===//
// Helpers
//===----------------------------------------------------------------------===//

string TestCppDir() {
	string file = __FILE__;
	auto pos = file.find_last_of("/\\");
	return file.substr(0, pos);
}

string OrtEngineFixtureDir() {
	return TestCppDir() + "/../fixtures/ort_engine";
}

string RepoFixtureDir() {
	return TestCppDir() + "/../fixtures";
}

bool FileExists(const string &path) {
	std::ifstream file(path, std::ios::binary);
	return file.good();
}

vector<char> ReadFileBytes(const string &path) {
	std::ifstream file(path, std::ios::binary);
	REQUIRE(file.good());
	return vector<char>((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
}

double GetNum(yyjson_val *value) {
	if (yyjson_is_int(value)) {
		return static_cast<double>(yyjson_get_sint(value));
	}
	if (yyjson_is_bool(value)) {
		return yyjson_get_bool(value) ? 1.0 : 0.0;
	}
	return yyjson_get_real(value);
}

//! Flatten an arbitrarily nested JSON array of numbers/bools.
void FlattenNumericArray(yyjson_val *value, vector<double> &out) {
	if (yyjson_is_arr(value)) {
		yyjson_val *element;
		yyjson_arr_iter iter;
		yyjson_arr_iter_init(value, &iter);
		while ((element = yyjson_arr_iter_next(&iter))) {
			FlattenNumericArray(element, out);
		}
		return;
	}
	out.push_back(GetNum(value));
}

struct YyDoc {
	explicit YyDoc(const vector<char> &bytes) {
		doc = yyjson_read(bytes.data(), bytes.size(), 0);
	}
	~YyDoc() {
		if (doc) {
			yyjson_doc_free(doc);
		}
	}
	yyjson_val *Root() {
		return doc ? yyjson_doc_get_root(doc) : nullptr;
	}
	yyjson_doc *doc = nullptr;
};

//===----------------------------------------------------------------------===//
// MLP fixture loading (WS-C's own committed fixture)
//===----------------------------------------------------------------------===//

struct MlpFixture {
	vector<char> graph;
	vector<char> weights; // the injection "arena"
	struct TensorSpec {
		string name;
		vector<int64_t> shape;
		idx_t offset;
		idx_t nbytes;
	};
	vector<TensorSpec> tensors;
	int64_t t = 0, h = 0, c = 0;
	vector<float> x, y, logits;
	vector<uint8_t> cat_mask; // bool storage
	int64_t train_size = 0, d = 0;
	double rtol = 1e-5;

	vector<TabFMTensorRef> Initializers() const {
		vector<TabFMTensorRef> refs;
		for (auto &tensor : tensors) {
			TabFMTensorRef ref;
			ref.name = tensor.name;
			ref.dtype = TabFMTensorDtype::F32;
			ref.shape = tensor.shape;
			ref.data = weights.data() + tensor.offset;
			ref.size_bytes = tensor.nbytes;
			refs.push_back(std::move(ref));
		}
		return refs;
	}

	TabFMRunInput RunInput() const {
		TabFMRunInput input;
		input.x = x.data();
		input.y = y.data();
		input.cat_mask = reinterpret_cast<const bool *>(cat_mask.data());
		input.t = t;
		input.h = h;
		input.train_size = train_size;
		input.d = d;
		return input;
	}
};

MlpFixture LoadMlpFixture() {
	auto dir = OrtEngineFixtureDir();
	MlpFixture fixture;
	fixture.graph = ReadFileBytes(dir + "/mlp_graph.onnx");
	fixture.weights = ReadFileBytes(dir + "/mlp_weights.f32");

	auto spec_bytes = ReadFileBytes(dir + "/mlp_expected.json");
	YyDoc doc(spec_bytes);
	auto *root = doc.Root();
	REQUIRE(root);

	auto *dims = yyjson_obj_get(root, "dims");
	REQUIRE(dims);
	fixture.t = static_cast<int64_t>(GetNum(yyjson_obj_get(dims, "T")));
	fixture.h = static_cast<int64_t>(GetNum(yyjson_obj_get(dims, "H")));
	fixture.c = static_cast<int64_t>(GetNum(yyjson_obj_get(dims, "C")));

	auto *tensors = yyjson_obj_get(root, "tensors");
	REQUIRE(yyjson_is_arr(tensors));
	yyjson_arr_iter iter;
	yyjson_arr_iter_init(tensors, &iter);
	yyjson_val *entry;
	while ((entry = yyjson_arr_iter_next(&iter))) {
		MlpFixture::TensorSpec spec;
		spec.name = yyjson_get_str(yyjson_obj_get(entry, "name"));
		vector<double> shape;
		FlattenNumericArray(yyjson_obj_get(entry, "shape"), shape);
		for (auto dim : shape) {
			spec.shape.push_back(static_cast<int64_t>(dim));
		}
		spec.offset = static_cast<idx_t>(GetNum(yyjson_obj_get(entry, "offset")));
		spec.nbytes = static_cast<idx_t>(GetNum(yyjson_obj_get(entry, "nbytes")));
		fixture.tensors.push_back(std::move(spec));
	}

	auto *inputs = yyjson_obj_get(root, "inputs");
	REQUIRE(inputs);
	vector<double> x_values, y_values, mask_values, logits_values;
	FlattenNumericArray(yyjson_obj_get(inputs, "x"), x_values);
	FlattenNumericArray(yyjson_obj_get(inputs, "y"), y_values);
	FlattenNumericArray(yyjson_obj_get(inputs, "cat_mask"), mask_values);
	FlattenNumericArray(yyjson_obj_get(root, "logits"), logits_values);
	fixture.train_size = static_cast<int64_t>(GetNum(yyjson_obj_get(inputs, "train_size")));
	fixture.d = static_cast<int64_t>(GetNum(yyjson_obj_get(inputs, "d")));
	fixture.rtol = GetNum(yyjson_obj_get(root, "rtol"));

	for (auto value : x_values) {
		fixture.x.push_back(static_cast<float>(value));
	}
	for (auto value : y_values) {
		fixture.y.push_back(static_cast<float>(value));
	}
	for (auto value : mask_values) {
		fixture.cat_mask.push_back(value != 0.0 ? 1 : 0);
	}
	for (auto value : logits_values) {
		fixture.logits.push_back(static_cast<float>(value));
	}
	REQUIRE(fixture.x.size() == static_cast<size_t>(fixture.t * fixture.h));
	REQUIRE(fixture.y.size() == static_cast<size_t>(fixture.t));
	REQUIRE(fixture.cat_mask.size() == static_cast<size_t>(fixture.h));
	REQUIRE(fixture.logits.size() == static_cast<size_t>(fixture.t * fixture.c));
	return fixture;
}

void RequireLogitsClose(const vector<float> &actual, const vector<float> &expected, double rtol, double atol) {
	REQUIRE(actual.size() == expected.size());
	double max_rel = 0.0;
	for (size_t i = 0; i < actual.size(); i++) {
		const double abs_diff = std::fabs(double(actual[i]) - double(expected[i]));
		if (abs_diff <= atol) {
			continue;
		}
		const double rel = abs_diff / std::max(std::fabs(double(expected[i])), 1e-12);
		max_rel = std::max(max_rel, rel);
	}
	INFO("max relative delta " << max_rel << " vs rtol " << rtol);
	REQUIRE(max_rel <= rtol);
}

} // anonymous namespace

//===----------------------------------------------------------------------===//
// Dtype hooks
//===----------------------------------------------------------------------===//

TEST_CASE("tabfm_ort_engine: dtype sizes and cast hooks", "[tabfm][ort_engine]") {
	REQUIRE(TabFMDtypeSize(TabFMTensorDtype::F32) == 4);
	REQUIRE(TabFMDtypeSize(TabFMTensorDtype::F16) == 2);
	REQUIRE(TabFMDtypeSize(TabFMTensorDtype::BF16) == 2);
	REQUIRE(TabFMDtypeSize(TabFMTensorDtype::I64) == 8);
	REQUIRE(TabFMDtypeSize(TabFMTensorDtype::BOOL) == 1);

	SECTION("f32 -> bf16 (GPU bf16 profile) and exact upcast back") {
		const float values[] = {0.0f, 1.0f, -1.0f, 3.140625f, 65504.0f, -0.15625f};
		auto bf16 = CastF32ToBF16(values, 6);
		REQUIRE(bf16[1] == 0x3f80); // 1.0f
		REQUIRE(bf16[2] == 0xbf80); // -1.0f
		auto round_tripped = CastBF16ToF32(bf16.data(), bf16.size());
		for (idx_t i = 0; i < 6; i++) {
			// bf16 keeps 8 mantissa bits -> <= 2^-8 relative error
			REQUIRE(std::fabs(round_tripped[i] - values[i]) <= std::fabs(values[i]) / 256.0 + 1e-30);
		}
	}

	SECTION("bf16 -> f32 upcast is exact on representable values (S02 path)") {
		const uint16_t bits[] = {0x3f80, 0xc000, 0x0000, 0x4049}; // 1.0, -2.0, 0.0, 3.140625
		auto floats = CastBF16ToF32(bits, 4);
		REQUIRE(floats[0] == 1.0f);
		REQUIRE(floats[1] == -2.0f);
		REQUIRE(floats[2] == 0.0f);
		REQUIRE(floats[3] == 3.140625f);
	}

	SECTION("f32 -> fp16 (RDNA3+ profile), round-to-nearest-even + saturation") {
		const float values[] = {0.0f, 1.0f, -2.0f, 65504.0f, 1e6f, 6.1035156e-05f};
		auto f16 = CastF32ToF16(values, 6);
		REQUIRE(f16[0] == 0x0000);
		REQUIRE(f16[1] == 0x3c00);
		REQUIRE(f16[2] == 0xc000);
		REQUIRE(f16[3] == 0x7bff); // fp16 max
		REQUIRE(f16[4] == 0x7c00); // overflow -> +inf
		REQUIRE(f16[5] == 0x0400); // smallest normal
	}
}

//===----------------------------------------------------------------------===//
// MIGraphX shape buckets
//===----------------------------------------------------------------------===//

TEST_CASE("tabfm_devices: MIGraphX shape buckets", "[tabfm][ort_engine][devices]") {
	auto bucket = MIGraphXShapeBucket(1, 1);
	REQUIRE(bucket.padded_t == 128);
	REQUIRE(bucket.padded_h == 16);

	bucket = MIGraphXShapeBucket(128, 16); // exact edges stay
	REQUIRE(bucket.padded_t == 128);
	REQUIRE(bucket.padded_h == 16);

	bucket = MIGraphXShapeBucket(129, 17); // just past an edge -> next bucket
	REQUIRE(bucket.padded_t == 512);
	REQUIRE(bucket.padded_h == 64);

	bucket = MIGraphXShapeBucket(4097, 300);
	REQUIRE(bucket.padded_t == 10000);
	REQUIRE(bucket.padded_h == 512);

	bucket = MIGraphXShapeBucket(10000, 512); // top edges
	REQUIRE(bucket.padded_t == 10000);
	REQUIRE(bucket.padded_h == 512);

	// above the largest bucket: unchanged (guardrail settings own the limit)
	bucket = MIGraphXShapeBucket(10001, 513);
	REQUIRE(bucket.padded_t == 10001);
	REQUIRE(bucket.padded_h == 513);

	REQUIRE_THROWS(MIGraphXShapeBucket(0, 16));
	REQUIRE_THROWS(MIGraphXShapeBucket(128, -1));
}

//===----------------------------------------------------------------------===//
// Device discovery + resolution
//===----------------------------------------------------------------------===//

TEST_CASE("tabfm_devices: discovery always yields the usable cpu row", "[tabfm][ort_engine][devices]") {
	auto devices = DiscoverDevices();
	REQUIRE(devices.size() >= 1);
	auto &cpu = devices[0];
	REQUIRE(cpu.device_id == "cpu");
	REQUIRE(cpu.ep == "CPUExecutionProvider");
	REQUIRE(!cpu.name.empty());
	REQUIRE(cpu.arch.empty());
	REQUIRE(cpu.vram_total == -1);
	REQUIRE(cpu.vram_free == -1);
	REQUIRE(cpu.usable);
#if !defined(TABFM_EP_CUDA) && !defined(TABFM_EP_MIGRAPHX)
	// cpu flavor: exactly the one row
	REQUIRE(devices.size() == 1);
#endif
}

TEST_CASE("tabfm_devices: ResolveDevice semantics", "[tabfm][ort_engine][devices]") {
	TabFMDeviceInfo cpu;
	cpu.device_id = "cpu";
	cpu.ep = "CPUExecutionProvider";
	cpu.usable = true;

	TabFMDeviceInfo cuda0;
	cuda0.device_id = "cuda:0";
	cuda0.ep = "CUDAExecutionProvider";
	cuda0.arch = "sm_89";
	cuda0.usable = true;

	TabFMDeviceInfo rocm0;
	rocm0.device_id = "rocm:0";
	rocm0.ep = "MIGraphXExecutionProvider";
	rocm0.arch = "gfx1100";
	rocm0.usable = true;

	SECTION("cpu flavor") {
		vector<TabFMDeviceInfo> devices {cpu};
		REQUIRE(ResolveDevice("cpu", devices, false, false).device_id == "cpu");
		REQUIRE(ResolveDevice("auto", devices, false, false).device_id == "cpu");
		// requesting a GPU lane on the cpu flavor: actionable flavor error
		try {
			ResolveDevice("cuda", devices, false, false);
			FAIL("expected an exception");
		} catch (std::exception &error) {
			string message = error.what();
			REQUIRE(message.find("does not carry 'cuda'") != string::npos);
			REQUIRE(message.find("install the 'cuda' flavor") != string::npos);
			REQUIRE(message.find("SET anofox_tabfm_device='cpu'") != string::npos);
		}
		REQUIRE_THROWS(ResolveDevice("rocm", devices, false, false));
	}

	SECTION("cuda flavor with a usable device") {
		vector<TabFMDeviceInfo> devices {cpu, cuda0};
		REQUIRE(ResolveDevice("cuda", devices, true, false).device_id == "cuda:0");
		REQUIRE(ResolveDevice("auto", devices, true, false).device_id == "cuda:0");
		REQUIRE(ResolveDevice("cpu", devices, true, false).device_id == "cpu");
		// carried flavor but the other GPU vendor requested
		REQUIRE_THROWS(ResolveDevice("rocm", devices, true, false));
	}

	SECTION("cuda flavor, device present but not usable") {
		cuda0.usable = false;
		vector<TabFMDeviceInfo> devices {cpu, cuda0};
		try {
			ResolveDevice("cuda", devices, true, false);
			FAIL("expected an exception");
		} catch (std::exception &error) {
			string message = error.what();
			REQUIRE(message.find("tabfm_devices()") != string::npos);
		}
		// auto falls back to the cpu lane
		REQUIRE(ResolveDevice("auto", devices, true, false).device_id == "cpu");
	}

	SECTION("rocm flavor") {
		vector<TabFMDeviceInfo> devices {cpu, rocm0};
		REQUIRE(ResolveDevice("rocm", devices, false, true).device_id == "rocm:0");
		REQUIRE(ResolveDevice("migraphx", devices, false, true).device_id == "rocm:0"); // alias
		REQUIRE(ResolveDevice("auto", devices, false, true).device_id == "rocm:0");
		// unsupported consumer card: usable=false -> explicit failure
		devices[1].usable = false;
		REQUIRE_THROWS(ResolveDevice("rocm", devices, false, true));
		REQUIRE(ResolveDevice("auto", devices, false, true).device_id == "cpu");
	}
}

//===----------------------------------------------------------------------===//
// Engine: session creation + forward pass (MLP fixture)
//===----------------------------------------------------------------------===//

TEST_CASE("tabfm_ort_engine: create session with injection and run", "[tabfm][ort_engine]") {
	auto fixture = LoadMlpFixture();

	TabFMSessionConfig config;
	config.intra_op_threads = 2;
	config.device_id = "cpu";
	config.model_tag = "mlp-fixture";

	auto session = CreateSession(fixture.graph.data(), fixture.graph.size(), fixture.Initializers(), config);
	REQUIRE(session);

	auto output = Run(*session, fixture.RunInput());
	REQUIRE(output.shape == vector<int64_t> {1, fixture.t, fixture.c});
	RequireLogitsClose(output.logits, fixture.logits, fixture.rtol, 1e-6);
}

TEST_CASE("tabfm_ort_engine: source arena freed after creation, reruns bit-identical (S02)",
          "[tabfm][ort_engine]") {
	auto fixture = LoadMlpFixture();

	TabFMSessionConfig config;
	config.intra_op_threads = 1;
	config.device_id = "cpu";
	config.model_tag = "mlp-fixture";

	auto session = CreateSession(fixture.graph.data(), fixture.graph.size(), fixture.Initializers(), config);

	// S02 contract: ORT copied both graph bytes and injected initializers
	// during session creation. Scribble over the sources — the moral
	// equivalent of freeing the safetensors arena.
	std::memset(fixture.weights.data(), 0x7f, fixture.weights.size());
	std::memset(fixture.graph.data(), 0x7f, fixture.graph.size());

	auto first = Run(*session, fixture.RunInput());
	auto second = Run(*session, fixture.RunInput());

	RequireLogitsClose(first.logits, fixture.logits, fixture.rtol, 1e-6);
	REQUIRE(first.logits.size() == second.logits.size());
	REQUIRE(std::memcmp(first.logits.data(), second.logits.data(), first.logits.size() * sizeof(float)) == 0);
}

TEST_CASE("tabfm_ort_engine: missing injection maps to the weights-not-loaded error", "[tabfm][ort_engine]") {
	auto fixture = LoadMlpFixture();

	TabFMSessionConfig config;
	config.device_id = "cpu";
	config.model_tag = "classification";

	// No initializers: the graph's external stubs point at a weights.bin that
	// never existed -> S02 negative control (a).
	try {
		CreateSession(fixture.graph.data(), fixture.graph.size(), {}, config);
		FAIL("expected an exception");
	} catch (std::exception &error) {
		string message = error.what();
		REQUIRE(message.find("model weights are not loaded") != string::npos);
		REQUIRE(message.find("CALL tabfm_load('classification')") != string::npos);
		REQUIRE(message.find("tabfm_download") != string::npos);
	}
}

TEST_CASE("tabfm_ort_engine: wrong-shape injection maps to the corrupted-checkpoint error", "[tabfm][ort_engine]") {
	auto fixture = LoadMlpFixture();

	TabFMSessionConfig config;
	config.device_id = "cpu";
	config.model_tag = "classification";

	// Corrupt W1: [4,8] -> [4,4] with a consistent byte count, so it passes
	// the size pre-check and must be rejected by ORT's replacement validation
	// (S02 negative control (b), "Replacement tensor's dimensions do not match").
	auto initializers = fixture.Initializers();
	REQUIRE(initializers[0].name == "W1");
	initializers[0].shape = vector<int64_t> {4, 4};
	initializers[0].size_bytes = 4 * 4 * sizeof(float);

	try {
		CreateSession(fixture.graph.data(), fixture.graph.size(), initializers, config);
		FAIL("expected an exception");
	} catch (std::exception &error) {
		string message = error.what();
		REQUIRE(message.find("corrupted or does not match") != string::npos);
		REQUIRE(message.find("tabfm_remove") != string::npos);
	}

	// Inconsistent byte count is caught before ORT even sees it.
	initializers = fixture.Initializers();
	initializers[0].size_bytes -= 4;
	REQUIRE_THROWS(CreateSession(fixture.graph.data(), fixture.graph.size(), initializers, config));
}

//===----------------------------------------------------------------------===//
// TabFMState lifecycle (HLD §6) — fake payloads, no ORT involved
//===----------------------------------------------------------------------===//

namespace {

shared_ptr<LoadedModel> MakeFakeModel(bool &freed_flag, const string &device = "cpu") {
	auto model = make_shared_ptr<LoadedModel>();
	model->session = shared_ptr<void>(new int(42), [&freed_flag](void *pointer) {
		freed_flag = true;
		delete static_cast<int *>(pointer);
	});
	model->device_id = device;
	model->dtype = "f32";
	model->bytes = 1234;
	return model;
}

} // anonymous namespace

TEST_CASE("tabfm_state: load / snapshot / unload-while-in-use / refcount release", "[tabfm][ort_engine][state]") {
	auto state = make_shared_ptr<TabFMState>();
	bool freed = false;

	state->Register("classification", MakeFakeModel(freed));
	REQUIRE(state->LoadedKeys() == vector<string> {"classification"});

	auto snapshot = state->Snapshot("classification");
	REQUIRE(snapshot);
	REQUIRE(snapshot->model_key == "classification");
	REQUIRE(!snapshot->evicted);
	REQUIRE(snapshot->bytes == 1234);

	// Unload while a predict holds a snapshot: marked evicted, gone from the
	// map, but the session survives until the snapshot releases.
	REQUIRE(state->Unload("classification"));
	REQUIRE(snapshot->evicted);
	REQUIRE(!freed);
	REQUIRE(state->Snapshot("classification") == nullptr);
	REQUIRE(state->LoadedKeys().empty());
	REQUIRE(!state->Unload("classification")); // second unload: not found

	snapshot.reset(); // the last predict finishes
	REQUIRE(freed);
}

TEST_CASE("tabfm_state: re-register replaces and evicts the old model", "[tabfm][ort_engine][state]") {
	auto state = make_shared_ptr<TabFMState>();
	bool freed_old = false, freed_new = false;

	state->Register("regression", MakeFakeModel(freed_old));
	auto old_snapshot = state->Snapshot("regression");

	state->Register("regression", MakeFakeModel(freed_new));
	REQUIRE(old_snapshot->evicted);
	REQUIRE(!freed_old); // still held
	auto new_snapshot = state->Snapshot("regression");
	REQUIRE(new_snapshot.get() != old_snapshot.get());
	REQUIRE(!new_snapshot->evicted);

	old_snapshot.reset();
	REQUIRE(freed_old);
	REQUIRE(!freed_new);
}

TEST_CASE("tabfm_state: UnloadAll evicts everything", "[tabfm][ort_engine][state]") {
	auto state = make_shared_ptr<TabFMState>();
	bool freed_a = false, freed_b = false;
	state->Register("classification", MakeFakeModel(freed_a));
	state->Register("regression", MakeFakeModel(freed_b));
	REQUIRE(state->LoadedKeys() == vector<string> {"classification", "regression"});

	REQUIRE(state->UnloadAll() == 2);
	REQUIRE(state->LoadedKeys().empty());
	REQUIRE(freed_a);
	REQUIRE(freed_b);
}

TEST_CASE("tabfm_state: shared across connections via the ObjectCache", "[tabfm][ort_engine][state]") {
	DuckDB db(nullptr);
	Connection connection_a(db);
	Connection connection_b(db);

	auto state_a = TabFMState::Get(*connection_a.context);
	auto state_b = TabFMState::Get(*connection_b.context);
	REQUIRE(state_a);
	REQUIRE(state_a.get() == state_b.get()); // one state per database instance

	bool freed = false;
	state_a->Register("classification", MakeFakeModel(freed));
	auto snapshot = state_b->Snapshot("classification"); // visible cross-connection
	REQUIRE(snapshot);
	REQUIRE(snapshot->device_id == "cpu");

	// per-device engine mutex: same object for the same device, distinct
	// objects for distinct devices (HLD §6 finalize serialization)
	REQUIRE(&state_a->DeviceMutex("cpu") == &state_b->DeviceMutex("cpu"));
	REQUIRE(&state_a->DeviceMutex("cpu") != &state_a->DeviceMutex("cuda:0"));

	snapshot.reset();
	state_a->UnloadAll();
	REQUIRE(freed);

	// a different database instance gets its own state
	DuckDB other_db(nullptr);
	Connection other_connection(other_db);
	REQUIRE(TabFMState::Get(*other_connection.context).get() != state_a.get());
}

//===----------------------------------------------------------------------===//
// Fixture-model parity vs golden.json (WS-A artifacts; skip when absent)
//===----------------------------------------------------------------------===//

namespace {

struct SafeTensorEntry {
	string key;
	vector<int64_t> shape;
	idx_t begin = 0;
	idx_t end = 0;
	string dtype;
};

//! Minimal safetensors parsing, TEST-ONLY (WS-B owns the production reader):
//! u64-LE header length, JSON header {key: {dtype, shape, data_offsets}},
//! offsets relative to the byte section after the header.
bool ParseSafetensors(const vector<char> &bytes, vector<SafeTensorEntry> &entries, idx_t &data_begin) {
	if (bytes.size() < 8) {
		return false;
	}
	uint64_t header_size = 0;
	std::memcpy(&header_size, bytes.data(), 8);
	if (8 + header_size > bytes.size()) {
		return false;
	}
	data_begin = 8 + static_cast<idx_t>(header_size);
	yyjson_doc *doc = yyjson_read(bytes.data() + 8, header_size, 0);
	if (!doc) {
		return false;
	}
	auto *root = yyjson_doc_get_root(doc);
	yyjson_obj_iter iter;
	yyjson_obj_iter_init(root, &iter);
	yyjson_val *key_value;
	while ((key_value = yyjson_obj_iter_next(&iter))) {
		string key = yyjson_get_str(key_value);
		auto *entry_value = yyjson_obj_iter_get_val(key_value);
		if (key == "__metadata__") {
			continue;
		}
		SafeTensorEntry entry;
		entry.key = key;
		entry.dtype = yyjson_get_str(yyjson_obj_get(entry_value, "dtype"));
		vector<double> shape;
		FlattenNumericArray(yyjson_obj_get(entry_value, "shape"), shape);
		for (auto dim : shape) {
			entry.shape.push_back(static_cast<int64_t>(dim));
		}
		vector<double> offsets;
		FlattenNumericArray(yyjson_obj_get(entry_value, "data_offsets"), offsets);
		if (offsets.size() != 2) {
			yyjson_doc_free(doc);
			return false;
		}
		entry.begin = static_cast<idx_t>(offsets[0]);
		entry.end = static_cast<idx_t>(offsets[1]);
		entries.push_back(std::move(entry));
	}
	yyjson_doc_free(doc);
	return true;
}

yyjson_val *GetAny(yyjson_val *object, const vector<const char *> &keys) {
	for (auto *key : keys) {
		if (auto *value = yyjson_obj_get(object, key)) {
			return value;
		}
	}
	return nullptr;
}

} // anonymous namespace

TEST_CASE("tabfm_ort_engine: fixture-model parity vs golden.json (WS-A, rtol 1e-4)", "[tabfm][ort_engine]") {
	auto dir = RepoFixtureDir();
	const string graph_path = dir + "/graph_fixture.onnx";
	const string safetensors_path = dir + "/model.safetensors";
	const string golden_path = dir + "/golden.json";
	if (!FileExists(graph_path) || !FileExists(safetensors_path) || !FileExists(golden_path)) {
		WARN("WS-A fixture model not present yet (test/fixtures/graph_fixture.onnx + model.safetensors + "
		     "golden.json) — skipping the parity test; it activates once WS-A lands");
		SUCCEED();
		return;
	}

	auto safetensors_bytes = ReadFileBytes(safetensors_path);
	vector<SafeTensorEntry> entries;
	idx_t data_begin = 0;
	if (!ParseSafetensors(safetensors_bytes, entries, data_begin) || entries.empty()) {
		WARN("could not parse " + safetensors_path + " with the test-only reader — skipping");
		SUCCEED();
		return;
	}
	for (auto &entry : entries) {
		if (entry.dtype != "F32") {
			WARN("fixture safetensors contains non-F32 tensor '" + entry.key + "' (" + entry.dtype +
			     ") — test-only reader handles F32; skipping");
			SUCCEED();
			return;
		}
	}

	// ONNX initializer name <- safetensors key. Prefer the WS-A tensor map if
	// present; otherwise apply the S06 convention (export wrapper prefixes
	// the checkpoint key with "m.").
	auto find_tensor_map = [&]() -> string {
		for (auto *candidate : {"tensor_map_fixture.json", "tensor_map.json"}) {
			if (FileExists(dir + "/" + candidate)) {
				return dir + "/" + candidate;
			}
		}
		return string();
	};
	std::unordered_map<string, string> key_to_name; // safetensors key -> ONNX name
	auto map_path = find_tensor_map();
	if (!map_path.empty()) {
		auto map_bytes = ReadFileBytes(map_path);
		YyDoc map_doc(map_bytes);
		auto *root = map_doc.Root();
		std::unordered_map<string, bool> known_keys;
		for (auto &entry : entries) {
			known_keys[entry.key] = true;
		}
		if (root && yyjson_is_obj(root)) {
			yyjson_obj_iter iter;
			yyjson_obj_iter_init(root, &iter);
			yyjson_val *key_value;
			while ((key_value = yyjson_obj_iter_next(&iter))) {
				auto *mapped = yyjson_obj_iter_get_val(key_value);
				if (!yyjson_is_str(mapped)) {
					continue; // tolerate richer map schemas
				}
				string left = yyjson_get_str(key_value);
				string right = yyjson_get_str(mapped);
				// direction-agnostic: one side is the safetensors key
				if (known_keys.count(right)) {
					key_to_name[right] = left;
				} else if (known_keys.count(left)) {
					key_to_name[left] = right;
				}
			}
		}
	}

	vector<TabFMTensorRef> initializers;
	for (auto &entry : entries) {
		TabFMTensorRef ref;
		auto mapped = key_to_name.find(entry.key);
		ref.name = mapped != key_to_name.end() ? mapped->second : ("m." + entry.key);
		ref.dtype = TabFMTensorDtype::F32;
		ref.shape = entry.shape;
		if (ref.shape.empty()) {
			ref.shape.push_back(1); // scalar tensors: ORT wants rank >= 0; keep byte count consistent
			if (entry.end - entry.begin != 4) {
				ref.shape.clear();
			}
		}
		ref.data = safetensors_bytes.data() + data_begin + entry.begin;
		ref.size_bytes = entry.end - entry.begin;
		initializers.push_back(std::move(ref));
	}

	auto golden_bytes = ReadFileBytes(golden_path);
	YyDoc golden_doc(golden_bytes);
	auto *golden = golden_doc.Root();
	if (!golden) {
		WARN("could not parse golden.json — skipping");
		SUCCEED();
		return;
	}
	auto *inputs = GetAny(golden, {"inputs", "input"});
	if (!inputs) {
		inputs = golden; // flat schema
	}
	auto *x_value = GetAny(inputs, {"x"});
	auto *y_value = GetAny(inputs, {"y"});
	auto *train_value = GetAny(inputs, {"train_size", "train"});
	auto *mask_value = GetAny(inputs, {"cat_mask"});
	auto *d_value = GetAny(inputs, {"d"});
	auto *logits_value = GetAny(golden, {"logits", "expected_logits", "logits_fp32", "output"});
	if (!x_value || !y_value || !train_value || !mask_value || !d_value || !logits_value) {
		WARN("golden.json schema differs from the expected S06 convention (inputs x/y/train_size/cat_mask/d + "
		     "logits) — skipping; align in integration");
		SUCCEED();
		return;
	}

	vector<double> x_doubles, y_doubles, mask_doubles, golden_logits;
	FlattenNumericArray(x_value, x_doubles);
	FlattenNumericArray(y_value, y_doubles);
	FlattenNumericArray(mask_value, mask_doubles);
	FlattenNumericArray(logits_value, golden_logits);
	const int64_t train_size = static_cast<int64_t>(GetNum(train_value));
	const int64_t d = static_cast<int64_t>(GetNum(d_value));
	const int64_t t = static_cast<int64_t>(y_doubles.size());
	if (t == 0 || x_doubles.size() % t != 0) {
		WARN("golden.json input shapes do not line up (|x| % T != 0) — skipping");
		SUCCEED();
		return;
	}
	const int64_t h = static_cast<int64_t>(x_doubles.size()) / t;

	vector<float> x(x_doubles.begin(), x_doubles.end());
	vector<float> y(y_doubles.begin(), y_doubles.end());
	vector<uint8_t> cat_mask;
	for (auto value : mask_doubles) {
		cat_mask.push_back(value != 0.0 ? 1 : 0);
	}
	if (cat_mask.size() < static_cast<size_t>(h)) {
		cat_mask.resize(static_cast<size_t>(h), 0);
	}

	auto graph_bytes = ReadFileBytes(graph_path);
	TabFMSessionConfig config;
	config.intra_op_threads = 2;
	config.device_id = "cpu";
	config.model_tag = "fixture";

	auto session = CreateSession(graph_bytes.data(), graph_bytes.size(), initializers, config);
	// S02: sources may be freed now; scribble to prove it for the big fixture too
	std::memset(safetensors_bytes.data(), 0x7f, safetensors_bytes.size());

	TabFMRunInput run_input;
	run_input.x = x.data();
	run_input.y = y.data();
	run_input.cat_mask = reinterpret_cast<const bool *>(cat_mask.data());
	run_input.t = t;
	run_input.h = h;
	run_input.train_size = train_size;
	run_input.d = d;

	auto output = Run(*session, run_input);
	REQUIRE(output.shape.size() == 3);
	REQUIRE(output.shape[1] == t);
	const int64_t c = output.shape[2];
	if (golden_logits.size() != static_cast<size_t>(t * c)) {
		WARN("golden.json logits length does not match the model output shape — skipping numeric comparison");
		SUCCEED();
		return;
	}

	// Golden parity convention (S06): compare prediction rows, i.e. rows
	// >= train_size, at rtol 1e-4.
	double max_rel = 0.0;
	for (int64_t row = train_size; row < t; row++) {
		for (int64_t cls = 0; cls < c; cls++) {
			const auto index = static_cast<size_t>(row * c + cls);
			const double expected = golden_logits[index];
			const double actual = output.logits[index];
			const double abs_diff = std::fabs(actual - expected);
			if (abs_diff <= 1e-6) {
				continue;
			}
			max_rel = std::max(max_rel, abs_diff / std::max(std::fabs(expected), 1e-12));
		}
	}
	INFO("fixture parity max relative delta over rows >= train_size: " << max_rel);
	REQUIRE(max_rel <= 1e-4);
}
