# Embed the weight-free artifacts in resources/ into the extension binary.
#
# Generates ${CMAKE_CURRENT_BINARY_DIR}/tabfm_bundled_resources.cpp implementing
# GetBundledResource() (see src/include/tabfm_bundled_resources.hpp) from the
# committed .onnx graphs + tensor maps, so the built-in model flow needs no
# companion files on disk. The bytes are Google-weight-free (license wall:
# S01/S06 — graphs are weight-free, tensor maps are name mappings only).
#
# Each file is registered under its filename; graphs additionally under their
# bare stem ("graph_classification") — the id the built-in manifest uses. A
# filesystem path never matches, so path-valued manifests fall through to disk.
#
# Output: sets TABFM_BUNDLED_RESOURCES_SRC to the generated source path.

set(_tabfm_res_dir "${CMAKE_CURRENT_SOURCE_DIR}/resources")
set(_tabfm_gen "${CMAKE_CURRENT_BINARY_DIR}/tabfm_bundled_resources.cpp")
set(_tabfm_inputs
    "graph_classification.onnx"
    "graph_regression.onnx"
    "graph_ext_classification.onnx"
    "graph_ext_regression.onnx"
    "graph_migraphx_classification.onnx"
    "graph_migraphx_regression.onnx"
    "tensor_map_classification.json"
    "tensor_map_regression.json")

# Re-run configure when a resource changes so the generated source stays fresh.
foreach(_f ${_tabfm_inputs})
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_tabfm_res_dir}/${_f}")
endforeach()

# Regenerate only when missing or stale (the hex embedding is a few seconds).
set(_tabfm_stale FALSE)
if(NOT EXISTS "${_tabfm_gen}")
    set(_tabfm_stale TRUE)
else()
    foreach(_f ${_tabfm_inputs})
        if("${_tabfm_res_dir}/${_f}" IS_NEWER_THAN "${_tabfm_gen}")
            set(_tabfm_stale TRUE)
        endif()
    endforeach()
endif()

if(_tabfm_stale)
    message(STATUS "anofox_tabfm: embedding resources -> ${_tabfm_gen}")
    set(_body "// Generated by cmake/embed_resources.cmake — do not edit.\n")
    string(APPEND _body "#include \"tabfm_bundled_resources.hpp\"\n\n")
    string(APPEND _body "namespace duckdb {\nnamespace anofox {\nnamespace {\n\n")
    set(_idx 0)
    set(_table "")
    foreach(_f ${_tabfm_inputs})
        set(_path "${_tabfm_res_dir}/${_f}")
        if(NOT EXISTS "${_path}")
            message(FATAL_ERROR "anofox_tabfm: bundled resource missing: ${_path}")
        endif()
        file(READ "${_path}" _hex HEX)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _arr "${_hex}")
        string(APPEND _body "static const unsigned char kRes${_idx}[] = {${_arr}};\n\n")
        string(APPEND _table "    {\"${_f}\", kRes${_idx}, sizeof(kRes${_idx})},\n")
        if(_f MATCHES "\\.onnx$")
            string(REGEX REPLACE "\\.onnx$" "" _stem "${_f}")
            string(APPEND _table "    {\"${_stem}\", kRes${_idx}, sizeof(kRes${_idx})},\n")
        endif()
        math(EXPR _idx "${_idx}+1")
    endforeach()
    string(APPEND _body "struct BundledEntry {\n")
    string(APPEND _body "    const char *id;\n    const unsigned char *data;\n    unsigned long size;\n};\n\n")
    string(APPEND _body "const BundledEntry kBundled[] = {\n${_table}};\n\n")
    string(APPEND _body "} // namespace\n\n")
    string(APPEND _body "BundledResource GetBundledResource(const string &id) {\n")
    string(APPEND _body "\tfor (const auto &e : kBundled) {\n")
    string(APPEND _body "\t\tif (id == e.id) {\n")
    string(APPEND _body "\t\t\treturn BundledResource{reinterpret_cast<const char *>(e.data), static_cast<idx_t>(e.size)};\n")
    string(APPEND _body "\t\t}\n\t}\n")
    string(APPEND _body "\treturn BundledResource{nullptr, 0};\n}\n\n")
    string(APPEND _body "} // namespace anofox\n} // namespace duckdb\n")
    file(WRITE "${_tabfm_gen}" "${_body}")
endif()

set(TABFM_BUNDLED_RESOURCES_SRC "${_tabfm_gen}")
